# 6.a

# Cholesky decomposition

In [1]:
from math import sqrt
import numpy as np
import time

def cholesky(A):
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]

    # Perform the Cholesky decomposition
    for i in range(n):
        for j in range(i+1):
            tmp_sum = sum(L[i][k] * L[j][k] for k in range(j))

            if (i == j): # Diagonal elements
                L[i][j] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][j] = (1.0 / L[j][j] * (A[i][j] - tmp_sum))
    return L

A = [[1, 10, 9],
     [10, 109, 60],
     [9, 60, 377]]

L = cholesky(A)

print("A:")
print(np.array(A))

print("L:")
print(np.array(L))

A:
[[  1  10   9]
 [ 10 109  60]
 [  9  60 377]]
L:
[[  1.   0.   0.]
 [ 10.   3.   0.]
 [  9. -10.  14.]]


In [2]:
def solveAXb_cholesky(A,b):
    n = len(A)
    L = cholesky(A)

    Y = [[0.0] for i in range(n)]
    X = [[0.0] for i in range(n)]

    for i in range(n):
        tmp_sum = sum(L[i][k] * Y[k][0] for k in range(i))
        Y[i][0] = (b[i][0]-tmp_sum)/L[i][i]

    for i in range(n-1,-1,-1):
        tmp_sum = sum(L[k][i] * X[k][0] for k in range(i+1,n))
        X[i][0] = (Y[i][0] - tmp_sum)/L[i][i]

    return X

A = [[9, 3, 6],
     [3, 10, 5],
     [6, 5, 21]]

b = [[3],
     [-5],
     [16]]

print("A:")
print(np.array(A))

print("B :")
print(np.array(b))

X = solveAXb_cholesky(A,b)
print("X :")
print(np.array(X))

A:
[[ 9  3  6]
 [ 3 10  5]
 [ 6  5 21]]
B :
[[ 3]
 [-5]
 [16]]
X :
[[ 0.]
 [-1.]
 [ 1.]]


In [3]:
A = [[0.0] * 1000 for i in range(1000)]
for i in range(999):
    A[i][i] = 5.0
    A[i+1][i] = -1.0
    A[i][i+1] = -1.0
A[999][999] = 5

b = [[1.0] for i in range(1000)]


print("A :")
print(np.array(A))

print("B :")
print(np.array(b))

start_time = time.time()
X = solveAXb_cholesky(A,b)
end_time = time.time()

print("X :")
print(np.array(X))

runtime = end_time - start_time
print("Runtime : " , runtime , " seconds ")

A :
[[ 5. -1.  0. ...  0.  0.  0.]
 [-1.  5. -1. ...  0.  0.  0.]
 [ 0. -1.  5. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  5. -1.  0.]
 [ 0.  0.  0. ... -1.  5. -1.]
 [ 0.  0.  0. ...  0. -1.  5.]]
B :
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [

# 6.b

# Thomas algorithm

In [4]:
import numpy as np

def thomas_algorithm (a , b , c , f):
    n = len (f)
    alpha = [0.0 for i in range(n)]
    beta = [0.0 for i in range(n)]
    alpha[0] = b[0]

    for i in range(1,n):
        beta[i] = a[i]/alpha[i-1]
        alpha[i] = b[i] - beta[i] * c[i-1]

    Y = [[0.0] for i in range(n)]
    X = [[0.0] for i in range(n)]

    Y[0][0] = f[0]
    for i in range(1,n):
        Y[i][0] = f[i] - beta[i] * Y[i-1][0]

    X[-1][0] = Y[-1][0]/alpha[-1]
    for i in range(n-2,-1,-1):
        X[i][0] = (Y[i][0] - c[i] * X[i+1][0])/alpha[i]

    return X

a = [0 ,16, 15,-2]
b = [4, -1, 8, 13]
c = [-1, 2, 5, 0]
f = [13, 65, 66, 9]

start_time = time.time()
X = thomas_algorithm (a , b , c , f)
end_time = time.time()

print ('X =' , np.array(X))

runtime = end_time - start_time
print ("Runtime : " , runtime , " seconds ")

X = [[4.]
 [3.]
 [2.]
 [1.]]
Runtime :  0.00012111663818359375  seconds 


In [5]:
a = [ -1 for i in range (1000) ]
a[0] = 0.0
b = [ 5 for i in range (1000) ]
c = [ -1 for i in range (1000) ]
c[-1] = 0.0
f = [ 1.0 for i in range (1000) ]

start_time = time.time()
X = thomas_algorithm (a , b , c , f)
end_time = time.time()

print (' X =' , np.array(X))

runtime = end_time - start_time
print ("Runtime : " , runtime , " seconds ")

 X = [[0.26376262]
 [0.31881308]
 [0.33030278]
 [0.33270082]
 [0.33320132]
 [0.33330578]
 [0.33332758]
 [0.33333213]
 [0.33333308]
 [0.33333328]
 [0.33333332]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 

# 6.c

In [6]:
A = [[0.0] * 1000 for i in range(1000)]
for i in range(999):
    A[i][i] = 5.0
    A[i+1][i] = -1.0
    A[i][i+1] = -1.0
A[999][999] = 5

b = [[1.0] for i in range(1000)]

print("A :")
print(np.array(A))

print("B :")
print(np.array(b))

start_time = time.time()
L = np.linalg.cholesky(A)
Y = np.linalg.solve(L,b)
X = np.linalg.solve(L.T,Y)
end_time = time.time()

print("X :")
print(np.array(X))

runtime = end_time - start_time
print("Runtime : " , runtime , " seconds ")

A :
[[ 5. -1.  0. ...  0.  0.  0.]
 [-1.  5. -1. ...  0.  0.  0.]
 [ 0. -1.  5. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  5. -1.  0.]
 [ 0.  0.  0. ... -1.  5. -1.]
 [ 0.  0.  0. ...  0. -1.  5.]]
B :
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [

In [7]:
start_time = time.time()
X = np.linalg.solve(A,b)
end_time = time.time()

print("X :")
print(np.array(X))

runtime = end_time - start_time
print("Runtime : " , runtime , " seconds ")

X :
[[0.26376262]
 [0.31881308]
 [0.33030278]
 [0.33270082]
 [0.33320132]
 [0.33330578]
 [0.33332758]
 [0.33333213]
 [0.33333308]
 [0.33333328]
 [0.33333332]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [

# واضح است که زمان اجرای الگوریتم ها با استفاده از توابع آماده به دلیل استفاده از پردازش های موازی و پیاده سازی های بهینه و استفاده از الگوریتم های تخصصی بسیار سریعتر است.