# 3

In [64]:
import numpy as np

def normalize(v):
    return v / np.sqrt(np.dot(v,v))

def gram_schmidt(V):
    if np.linalg.det(V) == 0:
        return "Warning: Vectors are linearly dependent!"
    m, n = V.shape
    Q = np.zeros((m, n))
    for j in range(n):
        Q[:,j] = V[:,j]
        for i in range(j):
            Q[:,j] -= (np.dot(V[:,j],Q[:,i]))/(np.linalg.norm(Q[:,i])**2) * Q[:,i] # متعامد سازی بردار ها
        Q[:,j] = normalize(Q[:,j]) #یکه سازی بردار ها
    return Q

V = np.array([[0, 1, 2],
              [1, 0, 1],
              [1, 1, 0]])

print(gram_schmidt(V))

[[ 0.          0.81649658  0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.70710678  0.40824829 -0.57735027]]


# 5

In [65]:
def QR_decomposition(V):

    if np.linalg.det(V) == 0:
        return "Warning: Columns are linearly dependent!"

    m, n = V.shape
    Q_hat = np.zeros((m, n))
    R_hat = np.zeros((m, n))
    D = np.zeros((m, n))

    for j in range(n):
        Q_hat[:,j] = V[:,j]
        for i in range(j):
            R_hat[i,j] = (np.dot(V[:,j],Q_hat[:,i]))/(np.linalg.norm(Q_hat[:,i])**2)
            Q_hat[:,j] -= R_hat[i,j] * Q_hat[:,i]
        R_hat[j,j] = 1
        D[j,j] = np.linalg.norm(Q_hat[:,j])
    Q = Q_hat @ np.linalg.inv(D)
    R = D @ R_hat
    return Q, R

V = np.array([[2, 1, -1],
              [1, 1, 0],
              [0, 2, 1]])


Q, R = QR_decomposition(V)
print("Q:\n")
print(Q)
print("R:\n")
print(R)

Q:

[[ 0.89442719 -0.09759001 -0.43643578]
 [ 0.4472136   0.19518001  0.87287156]
 [ 0.          0.97590007 -0.21821789]]
R:

[[ 2.23606798  1.34164079 -0.89442719]
 [ 0.          2.04939015  1.07349008]
 [ 0.          0.          0.21821789]]


# 6.A

In [66]:
def QR_decomposition(V):

    if np.linalg.det(V) == 0:
        return "Warning: Columns are linearly dependent!"

    m, n = V.shape
    Q_hat = np.zeros((m, n))
    R_hat = np.zeros((m, n))
    D = np.zeros((m, n))

    for j in range(n):
        Q_hat[:,j] = V[:,j]
        for i in range(j):
            R_hat[i,j] = (np.dot(V[:,j],Q_hat[:,i]))/(np.linalg.norm(Q_hat[:,i])**2)
            Q_hat[:,j] -= R_hat[i,j] * Q_hat[:,i]
        R_hat[j,j] = 1
        D[j,j] = np.linalg.norm(Q_hat[:,j])
    Q = Q_hat @ np.linalg.inv(D)
    R = D @ R_hat
    return Q, R

# 6.B

In [67]:
def hilbert(n):
    H = np.zeros((n, n))
    for i in range(1,n+1):
        for j in range(1,n+1):
            H[i-1,j-1] = 1/(i+j-1)
    return H

# 6.C

In [68]:
Q, R = QR_decomposition(hilbert(12))
print("Q:\n")
print(Q)
print("R:\n")
print(R)

Q:

[[ 0.79936673 -0.55256396  0.22311461 -0.07368422  0.02112684 -0.0053455
   0.00116094 -0.00110066 -0.00109499 -0.00109344 -0.00109287 -0.00109263]
 [ 0.39968337  0.23629494 -0.64382256  0.52450162 -0.28206801  0.11658335
  -0.03834229  0.03719628  0.03710841  0.03709276  0.03709152  0.03709393]
 [ 0.26645558  0.32838894 -0.30241651 -0.28279077  0.57629275 -0.48126582
   0.26515492 -0.26259177 -0.2626851  -0.26284749 -0.26298178 -0.26308651]
 [ 0.19984168  0.32317824 -0.05617549 -0.42067266  0.14751788  0.3721012
  -0.54680797  0.55557136  0.5579086   0.55915737  0.5599488   0.56049597]
 [ 0.15987335  0.29954875  0.08933358 -0.32684696 -0.21321449  0.37965956
   0.09011271 -0.11194305 -0.11606314 -0.11800726 -0.11916498 -0.11993597]
 [ 0.13322779  0.27403238  0.17368555 -0.1806813  -0.34694639  0.05751066
   0.40372125 -0.4087233  -0.409707   -0.41019969 -0.4105089  -0.41072445]
 [ 0.11419525  0.25057603  0.222329   -0.0401903  -0.32055268 -0.22115211
   0.23780459 -0.22305374 -0.2

# 6.D

In [69]:
Q, R = QR_decomposition(hilbert(20))
print("Q:\n")
print(Q)
print("R:\n")
print(R)

Q:

[[ 0.79151901 -0.55649982  0.23612165 -0.08494608  0.02760559 -0.00827892
   0.0023282   0.00200817 -0.00202928 -0.00203715 -0.00204146 -0.00204422
  -0.00204615 -0.00204757 -0.00204867 -0.00204953 -0.00205023 -0.0020508
  -0.00205128 -0.00205168]
 [ 0.3957595   0.20148028 -0.6133596   0.53994588 -0.32487503  0.15699551
  -0.06521324 -0.05602811  0.05668219  0.05693605  0.05707787  0.05716981
   0.05723451  0.05728251  0.05731947  0.05734873  0.0573724   0.05739188
   0.05740815  0.05742191]
 [ 0.26383967  0.29423025 -0.33534376 -0.17329659  0.51246724 -0.51530037
   0.35641668  0.2982095  -0.30256683 -0.30431231 -0.30530215 -0.30594888
  -0.30640603 -0.30674604 -0.30700819 -0.30721587 -0.30738391 -0.30752225
  -0.30763778 -0.30773543]
 [ 0.19787975  0.29263221 -0.1231938  -0.35871708  0.275852    0.162557
  -0.46500717 -0.34788254  0.35678066  0.36043168  0.36252066  0.36388976
   0.36485797  0.36557747  0.3661314   0.36656941  0.36692314  0.36721375
   0.36745594  0.36766024]
 [ 

In [70]:
Q, R = QR_decomposition(hilbert(100))
print("Q:\n")
print(Q)
print("R:\n")
print(R)

ValueError: too many values to unpack (expected 2)